server:
  port: 8080

spring:
  application:
    name: event-booking

  datasource:
    url: jdbc:h2:mem:eventbookingdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
